language: python
python:
  - "2.7"
  - "3.6"
# command to install dependencies
sudo: false
addons:
  apt:
    packages:
    - python-scipy
    - libblas-dev
    - liblapack-dev
    - gfortran
    - python-pip
    - python-openbabel
install:
  - "easy_install -U setuptools"
  - travis_wait pip install -r requirements-ci.txt --upgrade
  - pip install openbabel
# This is needed, otherwise, nosetests can't find the installed pymatgen C
# extensions.
before_script:
  - python setup.py develop
# command to run tests, e.g. python setup.py test
script: nosetests
notifications:
  email:
    recipients:
      - shyuep@gmail.com
    on_success: change
    on_failure: always
