language: python
python:
  - "2.7"
  - "3.1"
  - "3.2"
  - "3.3"
  - "3.4.1"
# command to install dependencies
install:
  - "easy_install -U setuptools"
  - "pip install -r requirements.txt"
# This is needed, otherwise, nosetests can't find the installed pymatgen C
# extensions.
before_script:
  - python setup.py develop
# command to run tests, e.g. python setup.py test
script: nosetests
notifications:
  email:
    recipients:
      - shyuep@gmail.com
    on_success: change
    on_failure: always
